# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('course', models.CharField(max_length=150)),
            ],
        ),
    ]
