# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170715_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=550),
        ),
    ]
