# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170722_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='subject',
        ),
    ]
