# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20170722_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='birthday',
            new_name='b_day',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
