# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20170729_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='b_day',
            new_name='birthday',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_description',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=550),
            preserve_default=False,
        ),
    ]
